services:
  mongo1:
    image: zahid03/my-mongo:8.0
    container_name: mongo1
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb-data/mongo1:/data/db
    networks:
      - mongo-cluster
    command: >
      mongod --replSet rs0 --bind_ip_all --keyFile /etc/mongodb-keyfile --auth
    restart: unless-stopped

  mongo2:
    image: zahid03/my-mongo:8.0
    container_name: mongo2
    ports:
      - "27018:27017"
    volumes:
      - ./mongodb-data/mongo2:/data/db
    networks:
      - mongo-cluster
    command: >
      mongod --replSet rs0 --bind_ip_all --keyFile /etc/mongodb-keyfile --auth
    restart: unless-stopped

  mongo3:
    image: zahid03/my-mongo:8.0
    container_name: mongo3
    ports:
      - "27019:27017"
    volumes:
      - ./mongodb-data/mongo3:/data/db
    networks:
      - mongo-cluster
    command: >
      mongod --replSet rs0 --bind_ip_all --keyFile /etc/mongodb-keyfile --auth
    restart: unless-stopped

networks:
  mongo-cluster:
    driver: bridge
